### ISSUE TITLE
Should this be moved to Bessels.jl?

### ISSUE THREAD

**Issue by oscardssmith** [cgeoga/BesselK.jl#9]
https://github.com/heltonmc/Bessels.jl is in the process of implementing all the bessel functions, so it might make sense for this code to become part of that library.

**Comment by cgeoga** [comment]
Hey, neat! This repo is hard-linked in a paper and so I don't think I will ever take it down, but I'm happy for whatever code is relevant to be copied over and put at note in the README here suggesting that users take a look there. I'm also interested to try and play with one of the new static compiling tools and use this repo to make libraries with `besselk` functions in particular because a lot of statisticians use R, and I'm hoping to eventually have a build step in this repo that somehow creates downloadable lib files that R packages can use.

From looking at the source, though, it seems like `Bessels.besselk` is only implemented for `Float{32,64}` and `BigFloat`. The main point of this implementation (and the reason it is so involved) is to get fast and decently accurate automatic derivatives with respect to `nu` with `ForwardDiff.jl`. The implementation of `besselk` itself in the base form gives up a few digits of accuracy in some places and is probably worse than your current one. If auto-derivatives are in scope for you, then maybe the extra complexity here is worth incorporating, but this is a lot more loc than your current form and I wouldn't blame you for not really wanting to introduce that into your codebase. 

At the very least, though, I do think a handful of things here could be useful to you. I use `Polynomials.jl` to compute the `U` polynomials directly here, for example, which might be some nice functionality to copy into your package (and I gather from skimming your source is currently a pain point).

What are your thoughts on all of that? I don't really know how the licensing stuff of just copying things over works, so if there is anything specific to discuss there please let me know.

**Comment by cgeoga** [comment]
Nice, Re: licensing. With regard to `Polynomials.jl` vs `Remez.jl`, that totally makes sense. What I mean more is that a function like [this](https://github.com/cgeoga/BesselK.jl/blob/main/src/besk_asv.jl#L5) might be of interest because I gather from comments like [this one](https://github.com/heltonmc/Bessels.jl/blob/master/src/besselk.jl#L56) that you guys currently do something manual to get them, that's all.

If you end up copying a nontrivial amount of the functionality here into `Bessels.jl` and don't end up modifying it very much, would you mind providing some attribution and maybe a link to this repo or to the associated paper or something somewhere in your README? I should actually have a real DOI for the paper pretty shortly---we just submitted a minor revision.

**Comment by oscardssmith** [comment]
We would obviously give attribution. Also, how much have you tested your `gamma` implementation? the SpecialFunctions one is really slow, so it would be great to have an accurate and fast one in pure Julia.

**Comment by cgeoga** [comment]
Awesome, thanks! Sorry, I just don't know what the norms are so I figured best to just ask.

With regard to the gamma function, not super well tested, although from very casual REPL fiddling it has never seemed inaccurate. If memory serves, though, it is in any case not faster than the one in `SpecialFunctions.jl`. I had an earlier implementation of some internal function that was way faster when I used it anyway, presumably because of the additional compiler optimizations that are possible when it is native Julia, but I ended up not using that code and so I just stuck with the base one. I would also love a faster and Julia-native `gamma`, though. It's actually the only reason we actually use `SpecialFunctions.jl` besides for `besselk` itself in the safe wrappers.

**Comment by heltonmc** [comment]
Cool package @cgeoga!!! The U-polynomials are such a pain and I like your implementation. I took the approach of just hard coding these so they are quickly evaluated using `evalpoly` at runtime. 

It looks like your code computes these once at perhaps during compilation? And then reuses them? I'm wondering how long it takes to evaluate these in your code? One of the issues with these is adding terms can really nonlinearly affect performance so I've kind of found if more than say 8 polynomials are required it's probably best to use a different method... And it's really hard to get these to work to guarantee error bounds. But they are useful for `besselk` for large orders and they can perhaps be used for `besselj` and `bessely` for x<nu. However, using these gives us the largest error of any of our routines...

**Comment by cgeoga** [comment]
Hey, thanks! I totally know what you mean about the perf problems. I originally stored coefficients in tuples, for example, but after a tuple size of, like, 8, I started getting allocations in the second derivatives, which I'm not okay with. It's clearly a complex performance dance there. I never was able to beat Polynomials.jl, which makes sense I suppose because that package rocks. I think NIST 10.41(iv) (specifically 10.41.13) should give some specific error bounds though. I also hear you about speed. It's definitely the slowest of our routines. It gives very nice automatic derivatives though, which is why we deal with it.

With regard to auto-generating them U polynomials, I have a file in `src/notinuse/`that literally generates a hard-coded `.jl` file, but still uses the symbolic operations in `Polynomials.jl` to get them for free. That might be of interest because it really wouldn't change much compared to what you're currently doing. I recognize it's a bit weird that `using BesselK` re-computes them every time. But it is, like, one second, so I haven't made it a priority to think harder about as of now.

With regard to arbitrary order, I have a lot to say. But none of it is particularly easy. You could skim the paper in the README for all the details, but the best strategy really depends on a lot on the size of the argument. The naive series type methods work pretty well for small arguments, and we have a representation we can push to maybe x=|8| or so, but we do that at the cost of several digits less than `eps` accuracy, which is not ideal. The argument range of, say, 5<x<20 is definitely the hardest part. Miller recursion seems to be a common tool, but that was one of the first things I tried in this project a couple years ago at this point (this is a slow-burning side hustle project) and for some reason I decided it wasn't going to work in our case of requiring accurate second derivatives w.r.t. nu. But I honestly don't remember why at this point. The speed of your method for the integer-order is insane to me. Like, its a full order of magnitude faster than using our code, which is in turn a factor of 2-4 faster than AMOS. So that's crazy. But I expect that you'll have to take a serious speed hit when you can't use the poly/rational approximations for K0 and K1.

**Comment by heltonmc** [comment]
Thanks for the information! Ya I originally started Bessels.jl because SpecialFunctions was just too slow where I had to calculated `besselj` over a million times.... recently we have been focusing a lot on accuracy but it is a tough bridge to traverse with bessel functions!

The allocations seems like a bug to me honestly (but that could be coming from the differentiation side)? I've definitely used coefficients up to 24 and haven't experienced any problems.

I just tried to do some benchmarks where I changed our code to use 6 coefficients. 
```julia
julia> @benchmark BesselK._besselk_asv(60, x, 6) setup=(x=rand()+12.0)
BenchmarkTools.Trial: 10000 samples with 952 evaluations.
 Range (min … max):  94.494 ns … 252.714 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     98.083 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   97.386 ns ±   3.170 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▁█▆            ▂▅▂█▇▃           ▁▂▁ ▂▁                       ▂
  ███▇▅▅▅▄▆▄▄▅▃▄▄███████▇▇▇█▆▇▅▇█▇████████▆▆▆▆▆▆▇▅▅▄▅▄▄▃▂▃▄▅▄▄ █
  94.5 ns       Histogram: log(frequency) by time       106 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark Bessels.besselk(60.0, x) setup=(x=rand()+12.0)
BenchmarkTools.Trial: 10000 samples with 987 evaluations.
 Range (min … max):  49.080 ns … 60.392 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     49.391 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   49.473 ns ±  0.360 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▁ ▂▅▅▇▅▆█▇▅▆▇▄▄▄▄▂▂▁                               ▁ ▂▁▂▁▁ ▃
  ██████████████████████▆▆▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅▅▆▅▆████████ █
  49.1 ns      Histogram: log(frequency) by time      50.9 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```
There definitely looks to be a good amount of speed to gain from hard coding these like we've done, but I definitely like your method to be able to dynamically determine the number of coefficients to use! I am actually looking at these coefficients again for `besselj` and `bessely` but I usually go through and determine the number of coefficients to use depending on the regime to avoid any loops. 

One thing that was interesting was that our methods didn't match.
```julia
julia> BesselK._besselk_asv(60, 12.0, 6)
7.732140264315337e32
julia> Bessels.besselk(60.0, 12.0)
7.732140264316242e32
```

Looking at the keisan calculator I get `7.732140264316248e32`. I didn't check our routine for different coefficients (so much easier to do with yours) but 
```julia
julia> BesselK._besselk_asv(60, 12.0, 5)
7.732140264322272e32
julia> BesselK._besselk_asv(60, 12.0, 6)
7.732140264315337e32
julia> BesselK._besselk_asv(60, 12.0, 7)
7.732140264316134e32
julia> BesselK._besselk_asv(60, 12.0, 8)
7.732140264316166e32
julia> BesselK._besselk_asv(60, 12.0, 9)
7.732140264316166e32
```
I'm wondering where the numerical differences arise from between the two codes? Perhaps from round off errors when building up the polynomials?

**Comment by heltonmc** [comment]
Anyway, getting a little too in the weeds right now! However, we'd love to have any help on Bessels.jl if you are interested. In regards to `besselk` we currently don't have a method for non-integer orders below nu<50 for any argument. I haven't spent any time on this though as I'm trying to get integer orders to work for all the functions first. I'll read your paper a little bit more carefully next!
-Michael

**Comment by cgeoga** [comment]
This is very interesting! For one, seriously impressive timings, as with everything else in the package. Looking more at the way you evaluate the uniform asymptotic expansion, I think you do something much more clever than I do in the code here. First looking at your implementation, I was confused because the `U_k` functions have a bunch of zero coefficients and you didn't have any coded in the `evalpoly` calls. But I now see how you've rearranged it and it is super clever. Not only would this probably help with avoiding allocations (which I agree is definitely because of the AD, and I assume there is just some compiler heuristic that eventually fails to be met and something gets boxed), but I wouldn't be surprised to see that this is meaningfully more numerically stable. That difference is probably the numerical difference you're seeing in the evaluations. 

Ah, I see your edit after typing this, which also more or less points this out. But yeah, I agree that that is likely the source of error. That's really a very nice strategy you have for the evaluation.

In principle, I'm very happy to help with stuff, but I don't expect to have a ton of time and so am a bit reluctant to make any commitments where you'd depend on me to do something. I kind of got myself pretty behind in actual dissertation stuff grinding out this project (which will probably be, like, a footnote in the actual document) and now am trying to do some catch-up. I also would guess that most of this code is not quite up to your accuracy standards, which are admirable. If nothing else I bet the Temme routine would meet your accuracy needs for, say, |z|<3, but it might be painfully slow compared to anything you do currently. If you're actively hacking on this stuff, maybe you could just @ me if you tinker with this code and any issues come up? I can definitely show up and discuss specific stuff.

**Comment by juliohm** [comment]
I am just jumping in to congratulate @cgeoga on this package 👏🏽  and to follow the discussion about the future of these joint efforts. As Chris pointed out in the JuliaCon talk, many packages currently use the besselk from SpecialFunctions.jl, and it would be nice to replace it with a pure Julia implementation that is cool and fast 🚀 BTW, I have the same use case as you Chris with the Matern variogram in GeoStats.jl. It would be nice to depend on your work instead.

I am probably missing something though: why SpecialFunctions.jl is still a dependency here? Can we have a pure Julia package without external dependencies implementing the function?

Thanks again for the great work.

**Comment by cgeoga** [comment]
Hey @juliohm, thanks so much for the kind words! I really appreciate them. I'm sorry if you asked that in the discord thing today during the live airing. I tried to register on discord and be there, but despite registering with my .edu email address I was insta-banned for some kind of "suspicious activity". I didn't even have my VPN on! I've never used discord before today and am now even more resolved to not touch that software with a ten foot pole. Here's to dreaming that the next JuliaCon uses, like, XMPP/Matrix/IRC/some other libre software in place of Discord some day in the future. But I doubt that's a priority.

The reason this package still depends on `SpecialFunctions` is because the `adbesselk` function returns `SpecialFunctions.besselk` when `v isa AbstractFloat` and when my implementation, `BesselK._besselk`, is less accurate. I have just recently scooped the integer-order `besselk` from `Bessels.jl` (with attribution, thanks @heltonmc and @oscardssmith), and I also brought over a cleaned up half-integer order one (see [this issue](https://github.com/heltonmc/Bessels.jl/issues/25)), so sometimes it isn't giving back `SpecialFunctions.besselk` when `v isa AbstractFloat`, but in general it is. I recognize that that's probably not what people are expecting and so it's not a great permanent solution. But we made some compromises of giving up the last couple digits of accuracy for big enough speed gains in the derivative, and I also kind of figure most people expect there `besselk` to be comparably accurate to `SpecialFunctions.besselk`, so ultimately I chose to disappoint with respect to speed instead of disappointing with accuracy by default.

Longer term, I think there are two likely outcomes and both will give a full Julia-native `besselk`:

(1) `Bessels.jl`, which does have AD in scope, manages an implementation that is faster and more accurate that gives derivatives that are at least as fast and as accurate as the ones here. In that case, the full solution will live there and this repo I think will really only live on as an archive because it is hard linked in a paper.

(2) `Bessels.jl` instead, at least for the time being, just offers super fast methods for `besselk` for `v isa AbstractFloat` or whatever. In that case, once there is an official release, I'll remove `SpecialFunctions` from the tree and instead depend on `Bessels.jl` and return their `besselk` whenever possible, so that `adbesselk` will be pure Julia even if it does still dispatch on the type of `v`.  That would be pretty sweet, and I could simplify the control flow and structure of my code once that happens and I'm in fact extra happy to return `Bessels.besselk` whenever possible.

I expect that there will probably be plenty of cross-pollination and that (1) is likely to happen at some point, as even my best branches can probably be improved and refined and then moved over. But (2) is probably going to be what happens for the next, like, 6-12 months or something. I'll be the first person to send in PRs to make (1) happen once we have a plan for that, so no need to worry about ecosystem fragmentation or anything.

@heltonmc @oscardssmith, would you say that's a fair description? Do you have anything to add?

**Comment by heltonmc** [comment]
Yes first thank you and congrats on the talk!! It's great to see interest in these topics.

There has been some discussion on [discourse](https://discourse.julialang.org/t/specialfunctions-jl-successor/35704) and in other issues at SpecialFunctions.jl on future directions. It appears that the general trend is to keep implementations in separate packages and keep SpecialFunctions.jl as stable as possible. So I'm not for sure if we will ever swap out implementations there, but that is a discussion for the maintainers over there. I definitely see pros to both and enough can't be said about the stability and reliability of the AMOS routines that users depend on. It will take time to develop that maturity and dependently which I hope we can get to.

With that said the non-native SpecialFunctions.jl routines are quite slow... Anytime I actually need to use a special function (e.g. `gamma`) it crushes performance. So we went ahead and implemented a `gamma` function in Julia which was 5x faster. Unfortunately, it just takes a long time to develop.... but I was looking at the `MaternVariogram` function which calls both `besselk` and `gamma` I would imagine a very big speedup just dropping in these routines.

The original intent for `Bessels.jl` was definitely to provide native implementation of `besselj`, `bessely`, `besseli`, `besselk`, `hankelh`, and the airy functions. There are a host of issues at `SpecialFunctions.jl` that relate to bessel functions that just can not be solved without native implementations, so I hope Bessels.jl can solve some of that. With that said the development plan I had in mind was:

- implementations for `besselj`, `bessely`, `besseli`, `besselk`, `hankelh` for all real and positive orders and arguments
- provide support for negative orders and arguments
- give `Float128` implementations
- implement for complex arguments
- implement complex orders
- derivatives with respect to argument
- derivatives with respect to order

So in some sense there is still quite a lot I want to accomplish but derivatives with respect to order were kind of one of the last things I had in mind. Now, I will definitely focus on what everyone would find most useful so please open issues at Bessels.jl with what you would want implemented and I can focus on that. Though I was hoping to at least provide a `0.1.0` release after I finish the first point (which should be soonish). So for everyone really wanting to take derivatives with respect to order of `besselk` please use this package for the near future. 😃 

But yes - I really would not like to reinvent the wheel as much as possible for `besselk` so please do send a PR and we can focus on cleaning up everything and getting the highest accuracy possible. I'm hoping to merge an implementation of `bessely` soon and will focus on getting the `besselk` version ready as well!

**Comment by juliohm** [comment]
Thank you @cgeoga , I appreciate the update and efforts. Will try to update the dependencies in GeoStats.jl to use your guys's work. Looking forward to removing all external dependencies from the stack 🙏🏽
